### ISSUE TITLE
Extra files

### ISSUE THREAD

**Issue by AEJester** [sindresorhus/write-json-file#10]
I made a file called `username.json`, and when I use `writeJsonFile('./username.json', {username: usrInput})`, it makes a whole other file called `username.json.6672923` (those numbers are random, but that was an example). Is there a fix?

**Comment by sindresorhus** [comment]
That's how atomic file writing works. We first write to a temporary file (like `username.json.6672923`) and then replace it with the actual destination file. This way if something happens during writing, the previous content of the destination file is not corrupted. If you're seeing `username.json.6672923` even after the writing is done, something is wrong. You either exited the process during writing or something else. If it's the latter, you could open an issue on https://github.com/npm/write-file-atomic

**Comment by AEJester** [comment]
The code in the issue description writes the data to the extra file, and does not write it to the original

**Comment by AEJester** [comment]
is or was there an error in the code above?

**Comment by kevva** [comment]
> The code in the issue description writes the data to the extra file, and does not write it to the original

Do you get any errors? How are you calling it? As @sindresorhus said, it will first write to the temporary file and then your destination file if successful.

**Comment by AEJester** [comment]
i don’t get any errors, and it is inside a signup function

**Comment by AEJester** [comment]
function signup() {
    //code with writeJsonFile()
}
