### ISSUE TITLE
Replaces File?

### ISSUE THREAD

**Issue by PokeTehDoge** [sindresorhus/write-json-file#13]
Instead of adding onto my json file, it just replaces everything in it.
Ex:
```json
{
"1":"1",
"2":"2",
"3":"3"
}
```
Then tell it to write onto it, and it just replaces everything there, with what I said to.

**Comment by SamVerschueren** [comment]
That's the point of the module. It writes an entire file. So it overwrites content.

**Comment by PokeTehDoge** [comment]
Well any modules you know that just adds onto it?

**Comment by SamVerschueren** [comment]
Nope. Also, that's just very difficult because it can't know how the file is stored. Is it an array? Is it an object? How should it append the data to the file? Just read the file, add the data to the object and write it back. That's the most safe operation.
