### ISSUE TITLE
New line at EOF

### ISSUE THREAD

**Issue by privatenumber** [sindresorhus/write-json-file#26]
I'm noticing that this adds a new line at the end of the file even when the existing JSON file doesn't have one. I am using this in `detectIndent` so I expected the whitespace to be left untouched.

Perhaps it could respect the EOF by default, or add a `detectEOF` option?

Happy to open a PR if we can decide on a direction with this issue.

**Comment by sindresorhus** [comment]
It should respect the EOF by default. No option needed, and a PR would be very welcome (test included) 👍
