### ISSUE TITLE
EPERM: operation not permitted, ...

### ISSUE THREAD

**Issue by jagsarai** [sindresorhus/write-json-file#28]
Using latest version of code 4.2.0, I'm getting this error on Windows x64 machine running windows 10. The initial write to json works, but any subsequent writes do not work. When I downgrade to version 3.0, the issue is gone. Any solutions? For now, Im going to use version 3.0.

**Comment by sindresorhus** [comment]
https://github.com/npm/write-file-atomic/issues/49

**Comment by arjunUnniumbath** [comment]
I had to migrate to version 4.0.0 to make it work.  I'm going to use 4 till the issue is fixed . 

Thank you for the prompt responses @sindresorhus

**Comment by arjunUnniumbath** [comment]
@sindresorhus  can you please update the write-file-atomic dependency .
