### ISSUE TITLE
How to append data to JSON file?

### ISSUE THREAD

**Issue by NetOperatorWibby** [sindresorhus/write-json-file#3]
Hi there, my question is the title of this issue. Nice plugin btw, works as expected.

**Comment by shinnn** [comment]
You can modify the data before passing it to the second argument of this function.

**Comment by NetOperatorWibby** [comment]
...how would I do that?

**Comment by shinnn** [comment]
For example, when your original data looks like:

```js
const yourData = {lastName: 'John'};
```

You can add `familyName` properrty like this:

```
yourData.familyName = 'Smith';
```

======

Use https://stackoverflow.com/ for further information. "How to append data to JavaScript objects?" is not an issue report for this project but just a JavaScript language support question.

**Comment by NetOperatorWibby** [comment]
I was already looking for answers on SO, but figured I'd ask here since I'm using the plugin. Your answer isn't quite what I'm looking for, but I'll figure it out.
