### ISSUE TITLE
Plugin is not working in Vue.js

### ISSUE THREAD

**Issue by sadashivm** [sindresorhus/write-json-file#35]
Hello,
Im trying to implement your npm package in my code, but it is not working. I'm getting the below error.

![image](https://user-images.githubusercontent.com/10355473/101172280-faf73080-3666-11eb-800a-f67780edffba.png)

![image](https://user-images.githubusercontent.com/10355473/101172342-0f3b2d80-3667-11eb-9f36-41427c43f65b.png)

I kept data.josn in same path where App.vue file is exist.

**Comment by sindresorhus** [comment]
This package works fine in Node.js. It's up to you to figure this out or ask in the Vue support channels. This is a problem with your build set up, not this package.
