### ISSUE TITLE
Data not getting written to Json file

### ISSUE THREAD

**Issue by arjunUnniumbath** [sindresorhus/write-json-file#37]
The module is not working since few days. 
As part of debugging, I created a foo.json and tried out the sample code given in the documentation. 

The file is still turning up as blank.  There is no error message being thrown too. 

**nodejs version is : v9.8.0  , os in windows 10 .** 

Is there any open issues in this regard ? 

```
const writeJsonFile = require('write-json-file');

var test = async function () {
const writeJsonFile = require('write-json-file');
    await writeJsonFile('foo.json', {foo: true});
}
test();
```

**Comment by arjunUnniumbath** [comment]
@sindresorhus

**Comment by sindresorhus** [comment]
Try with the latest Node.js version.

**Comment by arjunUnniumbath** [comment]
Thank you for the prompt response . 
working in "v12.18.4 " . but we have a dependency related issue to move the project above 10 :( 

is there any other workaround  ? @sindresorhus

**Comment by sindresorhus** [comment]
Not really. I don't have the time to look into a fix right now and it's also not a priority as I intend to target Node.js 12 and later in a few months. Node.js 10 is soon out of LTS, which means no support, even from the Node.js core team. Time to upgrade to Node.js 12 or later.

**Comment by arjunUnniumbath** [comment]
Thank you  for the quick revert ! Will have to remove lots of dependencies in my project  to be compatible with higher version I guess !!!! Thank you for the help !

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/write-json-file/releases/tag/v5.0.0

**Comment by arjunUnniumbath** [comment]
Thank you @sindresorhus
