### ISSUE TITLE
Module not found: Can't resolve 'node:fs'

### ISSUE THREAD

**Issue by ClusterH** [sindresorhus/write-json-file#38]
After install this package in react.js project, got error during compile like that:

```
Failed to compile.

./node_modules/write-json-file/index.js
Module not found: Can't resolve 'node:fs' in 'D:\MY_DAILY\Projects\ReactProject\node_modules\write-json-file'
```

Tried add something to `package.json`, but does not effect, still same.

`"browser": {
    "crypto": false,
    "fs": false,
    "path": false,
    "os": false,
    "net": false,
    "stream": false,
    "tls": false
  },`

**Comment by sindresorhus** [comment]
This is a problem with the build tool you're using.

https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c
