### ISSUE TITLE
Is it time to drop the Promise polyfill?

### ISSUE THREAD

**Issue by LinusU** [sindresorhus/write-json-file#4]
This library depends on `pinkie-promise` which in turns depends on `pinkie` which is a Promise polyfill. It's only used on Node 0.10 and lower though, but still gets installed on every version.

Is it time to drop support and start using only native Promises? Is it time to step into the future? 🙌 👾

**Comment by sindresorhus** [comment]
Unfortunately not yet. I depend on this indirectly in https://www.npmjs.com/package/ava-init which is going to have to support Node.js 0.10 for at least a couple of months more...

**Comment by LinusU** [comment]
Ah, I understand, hopefully soon :)

Another thing that I thought about is the usage of mkdirp, I'm not saying that it's right or wrong, but for my specific use case it wasn't warranted. Do you feel that it's inside the scope of this package to do that?

Anyways, great lib! Do you want me to close the issue or should we keep it open?

**Comment by sindresorhus** [comment]
Yes, the package is meant to make it easy to write JSON, and I don't want to think about having to create directories.

Can keep it open so I don't forget.

**Comment by LinusU** [comment]
Cool, thanks for the quick answers 🙌

**Comment by SamVerschueren** [comment]
@sindresorhus because es2015ifying a module requires a major semver bump, you could still rely on it in `ava-init`.

**Comment by sindresorhus** [comment]
@SamVerschueren That's a good point. I guess we can do it then. PR welcome.
