### ISSUE TITLE
For anyone wondering...

### ISSUE THREAD

**Issue by benzmuircroft** [sindresorhus/write-json-file#6]
this whole module can be substituted with

```
var wf=require('write-json-file');
wf(__dirname+'file.json',JSON.stringify({a:'b',c:{d:'e'}},undefined,'\t'),function(e){});

```
You even get a proper callback with an error object unlike this module!

**Comment by SamVerschueren** [comment]
Actually no, because you are using this module with a callback which is not supported. What you probably mean is 

```js
const fs = require ('fs');
fs.writeFile(__dirname+'file.json',JSON.stringify({a:'b',c:{d:'e'}},undefined,'\t'),function(e){});
```

Totally do that if you like callbacks.
