### ISSUE TITLE
Typescript definition?

### ISSUE THREAD

**Issue by DenisCarriere** [sindresorhus/write-json-file#8]
@sindresorhus Any interest to include a Typescript definition to this repo? The API shouldn't be changing too much and the definition should be pretty straight forward.

I've already got something working so far, I can send a PR if you 👍 

**index.d.ts**
```typescript
interface Options {
    indent?: string | number
    detectIndent?: boolean
    sortKeys?: boolean
    replacer?: Function
    mode?: number
}

/**
 * https://github.com/sindresorhus/write-json-file
 */
declare function writeJsonFile(filepath: string, data: any, options?: Options): Promise<void>;
declare namespace writeJsonFile {
    function sync(filepath: string, data: any, options?: Options): void;
}
export = writeJsonFile;
```

**Comment by SamVerschueren** [comment]
Sorry, it's better to publish them to DefinitelyTyped https://github.com/sindresorhus/ama/issues/439

**Comment by DenisCarriere** [comment]
Works for me! just figured I'd ask, it's only ~10 LOC

**Comment by sindresorhus** [comment]
I now accept TypeScript definitions if anyone looking is interested in submitting it here.

See: https://github.com/sindresorhus/ama/issues/439#issuecomment-414212229

Please follow this guide: https://github.com/sindresorhus/typescript-definition-style-guide
